# Book Recommender System

In [1]:
import numpy as np
import pandas as pd

In [2]:
books = pd.read_csv('data/books.csv', encoding='latin-1')

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12652\1563079984.py:1: DtypeWarning: Columns (0: Year-Of-Publication) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('data/books.csv', encoding='latin-1')

In [3]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [4]:
books.shape

(271360, 8)

In [5]:
users = pd.read_csv('data/users.csv')

In [6]:
users.head(2)

   User-ID                   Location   Age
0        1         nyc, new york, usa   NaN
1        2  stockton, california, usa  18.0

In [7]:
users.rename(columns={'User-Id': 'user_id', 'Location': 'location', 'Age': 'age'}, inplace=True)

In [8]:
ratings = pd.read_csv('data/ratings.csv')

In [9]:
ratings.head(2)

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5

In [10]:
ratings.rename(columns={'User-ID': 'user_id', 'Book-Rating': 'book_rating'}, inplace=True)

In [11]:
ratings.columns

Index(['user_id', 'ISBN', 'book_rating'], dtype='str')

In [12]:
print(books.shape)
print(users.shape)
print(ratings.shape)

(271360, 8)
(278858, 3)
(1149780, 3)

In [13]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [14]:
users.isnull().sum()

User-ID          0
location         0
age         110762
dtype: int64

In [15]:
ratings.isnull().sum()

user_id        0
ISBN           0
book_rating    0
dtype: int64

In [16]:
books.duplicated().sum()

np.int64(0)

In [17]:
ratings.duplicated().sum()

np.int64(0)

In [18]:
users.duplicated().sum()

np.int64(0)

## Let's find top 50 popular books based on max average ratings which are rated by more than 250 users

In [19]:
ratings_with_name=ratings.merge(books, on='ISBN')

In [20]:
ratings_with_name.head(2)

,user_id,ISBN,book_rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,276726,0155061224,5,Rites of Passage,Judith Rae,2001,Heinle,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...

In [21]:
num_rating_df=ratings_with_name.groupby('Book-Title')['book_rating'].count().sort_values(ascending=False).reset_index()

In [22]:
num_rating_df.head(2)

                  Book-Title  book_rating
0                Wild Animus         2502
1  The Lovely Bones: A Novel         1295

In [23]:
num_rating_df.rename(columns={'book_rating': 'num_ratings'}, inplace=True)

In [24]:
avg_rating_df=ratings_with_name.groupby('Book-Title')['book_rating'].mean().sort_values(ascending=False).reset_index()
avg_rating_df.rename(columns={'book_rating': 'avg_rating'}, inplace=True)

In [25]:
avg_rating_df.head(2)

                                          Book-Title  avg_rating
0  Timelock: How Life Got So Hectic and What You ...        10.0
1                         Timelines of World History        10.0

In [26]:
popular_df=num_rating_df.merge(avg_rating_df, on='Book-Title')
popular_df.head(2)

                  Book-Title  num_ratings  avg_rating
0                Wild Animus         2502    1.019584
1  The Lovely Bones: A Novel         1295    4.468726

In [27]:
popular_df=popular_df[popular_df['num_ratings']>250].sort_values('avg_rating', ascending=False).head(50)

In [28]:
popular_df.shape

(50, 3)

In [29]:
books.shape

(271360, 8)

In [30]:
books.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='str')

In [31]:
popular_df=popular_df.merge(books, on='Book-Title').drop_duplicates('Book-Title')

In [32]:
popular_df.shape

(50, 10)

In [33]:
popular_df = popular_df[['Book-Title', 'Book-Author', 'Image-URL-M', 'num_ratings', 'avg_rating']]

In [34]:
# top 50 popular books
popular_df.shape

(50, 5)

In [35]:
#
import pickle
pickle.dump(popular_df, open('popular_books.pkl', 'wb'))

### Finding each users with their total ratings on books

In [36]:
ratings['user_id'].value_counts()

user_id
11676     13602
198711     7550
153662     6109
98391      5891
35859      5850
          ...
276697        1
276706        1
276709        1
276721        1
276723        1
Name: count, Length: 105283, dtype: int64

value_counts() returns a series with index and value
considering only those users who rated more than 200 books

In [37]:
ratings['user_id'].value_counts()>200

user_id
11676      True
198711     True
153662     True
98391      True
35859      True
          ...
276697    False
276706    False
276709    False
276721    False
276723    False
Name: count, Length: 105283, dtype: bool

Storing the returned series in variable x with user_id as index of the series and boolean value(true,false) as values

In [38]:
x = ratings['user_id'].value_counts()>200

In [39]:
x.shape

(105283,)

In [40]:
# keeping only the users who have rated more than 200 books
y = x[x].index

In [41]:
y.shape

(899,)

### Only 899 users are our real users. Because we will consider their ratings as valid ratings

In [42]:
# filtering the ratings dataframe to only include users who have rated more than 200 books
ratings = ratings[ratings['user_id'].isin(y)]

In [43]:
ratings.shape

(526356, 3)

In [44]:
# merging the ratings and books dataframes on the ISBN column
ratings_with_books = ratings.merge(books, on='ISBN')

In [45]:
ratings_with_books.shape

(487671, 10)

#### ratings_with_books has less rows than ratings because some of the ISBNs in ratings do not have a corresponding entry in books

In [46]:
ratings_with_books.head()

,user_id,ISBN,book_rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...
1,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,http://images.amazon.com/images/P/0026217457.0...,http://images.amazon.com/images/P/0026217457.0...,http://images.amazon.com/images/P/0026217457.0...
2,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning,http://images.amazon.com/images/P/003008685X.0...,http://images.amazon.com/images/P/003008685X.0...,http://images.amazon.com/images/P/003008685X.0...
3,277427,0030615321,0,"Ask for May, Settle for June (A Doonesbury book)",G. B. Trudeau,1982,Henry Holt &amp; Co,http://images.amazon.com/images/P/0030615321.0...,http://images.amazon.com/images/P/0030615321.0...,http://images.amazon.com/images/P/0030615321.0...
4,277427,0060002050,0,On a Wicked Dawn (Cynster Novels),Stephanie Laurens,2002,Avon Books,http://images.amazon.com/images/P/0060002050.0...,http://images.amazon.com/images/P/0060002050.0...,http://images.amazon.com/images/P/0060002050.0...

In [47]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [48]:
# counting the number of ratings for each book. It is a series with book titles as index and number of ratings as values
number_of_ratings = ratings_with_books.groupby('Book-Title')['book_rating'].count()

In [49]:
number_of_ratings

Book-Title
 A Light in the Storm: The Civil War Diary of Amelia Martin, Fenwick Island, Delaware, 1861 (Dear America)    2
 Always Have Popsicles                                                                                        1
 Apple Magic (The Collector's series)                                                                         1
 Beyond IBM: Leadership Marketing and Finance for the 1990s                                                   1
 Clifford Visita El Hospital (Clifford El Gran Perro Colorado)                                                1
                                                                                                             ..
Ã?Ã?ber die Pflicht zum Ungehorsam gegen den Staat.                                                         3
Ã?Ã?lpiraten.                                                                                               1
Ã?Ã?rger mit Produkt X. Roman.                                                                              1
Ã?Ã?stlich der Berge.                                                                                       1
Ã?Ã?thique en toc                                                                                           1
Name: book_rating, Length: 160269, dtype: int64

In [50]:
# resetting the index of the series to convert it back to a dataframe
number_of_ratings = number_of_ratings.reset_index()
number_of_ratings.head()

                                          Book-Title  book_rating
0   A Light in the Storm: The Civil War Diary of ...            2
1                              Always Have Popsicles            1
2               Apple Magic (The Collector's series)            1
3   Beyond IBM: Leadership Marketing and Finance ...            1
4   Clifford Visita El Hospital (Clifford El Gran...            1

In [51]:
number_of_ratings.rename(columns={'book_rating': 'number_of_ratings'}, inplace=True)

In [52]:
number_of_ratings.head(2)
number_of_ratings.shape

(160269, 2)

In [54]:
# calculating the average rating for each book. It is a series with book titles as index and average rating as values
avg_ratings = ratings_with_books.groupby('Book-Title')['book_rating'].mean().reset_index()
avg_ratings.rename(columns={'book_rating': 'avg_rating'}, inplace=True)

In [55]:
avg_ratings.head(2)

                                          Book-Title  avg_rating
0   A Light in the Storm: The Civil War Diary of ...         4.5
1                              Always Have Popsicles         0.0

In [57]:
final_ratings = ratings_with_books.merge(number_of_ratings, on='Book-Title')

In [58]:
final_ratings.shape

(487671, 11)

In [59]:
final_ratings.head()

,user_id,ISBN,book_rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,number_of_ratings
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,82
1,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,http://images.amazon.com/images/P/0026217457.0...,http://images.amazon.com/images/P/0026217457.0...,http://images.amazon.com/images/P/0026217457.0...,7
2,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning,http://images.amazon.com/images/P/003008685X.0...,http://images.amazon.com/images/P/003008685X.0...,http://images.amazon.com/images/P/003008685X.0...,1
3,277427,0030615321,0,"Ask for May, Settle for June (A Doonesbury book)",G. B. Trudeau,1982,Henry Holt &amp; Co,http://images.amazon.com/images/P/0030615321.0...,http://images.amazon.com/images/P/0030615321.0...,http://images.amazon.com/images/P/0030615321.0...,1
4,277427,0060002050,0,On a Wicked Dawn (Cynster Novels),Stephanie Laurens,2002,Avon Books,http://images.amazon.com/images/P/0060002050.0...,http://images.amazon.com/images/P/0060002050.0...,http://images.amazon.com/images/P/0060002050.0...,13

In [60]:
# keeping only those books which have more than 50 ratings
final_ratings = final_ratings[final_ratings['number_of_ratings'] > 50]

In [61]:
final_ratings.shape

(59903, 11)

In [62]:
# check for duplicates in final_ratings 
final_ratings.duplicated().any() # there are no duplicates

np.False_

In [64]:
# creating a pivot table with book titles as index, user ids as columns and book ratings as values
book_pivot = final_ratings.pivot_table(columns='user_id', index='Book-Title', values='book_rating')

In [65]:
book_pivot.shape

(703, 888)

### There are 703 books(reviewed more than 50 times by users) and 888 users(who reviewed more than 200 books)

In [66]:
book_pivot.head()

user_id,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84 Charing Cross Road,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN

In [67]:
book_pivot.fillna(0, inplace=True)

user_id,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84 Charing Cross Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,7.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [68]:
book_pivot.head(2)

user_id,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [69]:
from scipy.sparse import  csr_matrix
book_sparse = csr_matrix(book_pivot) # converting the pivot table to a sparse matrix for efficient storage and computation
book_sparse.shape

(703, 888)

### Trial 1: Using KNN algorithm

In [70]:
from sklearn.neighbors import NearestNeighbors
model = NearestNeighbors(algorithm='brute')

In [71]:
model.fit(book_sparse)

NearestNeighbors(algorithm='brute')

In [72]:
# finding the 5 nearest neighbors for the first book in the pivot table
# values.reshape(1, -1)

#     Original: 1D array → shape like (features,)

#     After reshape: 2D array → shape (1, features)
# distances are distance between books in hyperspace & suggestions are the indices of the nearest neighbors
distances, suggestions = model.kneighbors(book_pivot.iloc[224,:].values.reshape(1,-1), n_neighbors=6)

In [73]:
distances

array([[ 0.        , 67.73129098, 67.77802823, 72.22091879, 76.03909813,
        76.55027397]])

In [74]:
suggestions

array([[224, 227, 225, 228, 173, 277]])

In [75]:
for i in range(len(suggestions)):
    print(book_pivot.index[suggestions[i]])

Index(['Harry Potter and the Chamber of Secrets (Book 2)',
       'Harry Potter and the Prisoner of Azkaban (Book 3)',
       'Harry Potter and the Goblet of Fire (Book 4)',
       'Harry Potter and the Sorcerer's Stone (Book 1)', 'Exclusive',
       'Jacob Have I Loved'],
      dtype='str', name='Book-Title')

In [76]:
book_pivot.index[1]

'1st to Die: A Novel'

In [77]:
'Harry Potter and the Chamber of Secrets (Book 2)' in book_pivot.index

True

In [78]:
book_pivot.index.get_loc('Animal Farm')

47

In [79]:
def recommend_books(book_name):
    book_index = book_pivot.index.get_loc(book_name)
    distances, suggestions = model.kneighbors(book_pivot.iloc[book_index,:].values.reshape(1,-1), n_neighbors=6) 
    for i in range(len(suggestions[0])):
        if book_pivot.index[suggestions[0][i]] != book_name:
            print(book_pivot.index[suggestions[0][i]])

In [80]:
recommend_books('Animal Farm')

Exclusive
Jacob Have I Loved
Pleading Guilty
No Safe Place
Winter Moon

## Trail 2: Using cosine similarity

In [81]:
from sklearn.metrics.pairwise import cosine_similarity

In [82]:
# calculating the cosine similarity between the books based on their ratings by users
similarity_score = cosine_similarity(book_pivot)
similarity_score.shape

(703, 703)

In [83]:
book_pivot.index[0] # The first book in the pivot table is '1984' and its index is 0

'1984'

In [84]:
# the similarity scores for the first book with all other books
similarity_score[0]

array([1.        , 0.09259251, 0.01122267, 0.        , 0.08708674,
       0.04847394, 0.02550819, 0.0730769 , 0.11207963, 0.02998295,
       0.03371421, 0.02134876, 0.06139476, 0.01868845, 0.0825378 ,
       0.06731328, 0.10252858, 0.04630962, 0.02314465, 0.10542489,
       0.        , 0.12738003, 0.0711696 , 0.05634353, 0.07792927,
       0.        , 0.06328801, 0.12354715, 0.06986576, 0.11043489,
       0.05842928, 0.01354254, 0.        , 0.07322549, 0.04157401,
       0.01419341, 0.0872911 , 0.01630857, 0.02242419, 0.07048157,
       0.10736773, 0.04839326, 0.07380827, 0.07787765, 0.07906263,
       0.0497226 , 0.05042114, 0.28393467, 0.08989427, 0.09244761,
       0.1152654 , 0.10803669, 0.0697622 , 0.04006742, 0.01765755,
       0.        , 0.05028458, 0.00501224, 0.07003198, 0.04718206,
       0.1738128 , 0.        , 0.01140469, 0.02743558, 0.03767901,
       0.11453863, 0.14358757, 0.        , 0.07197121, 0.12011177,
       0.06081257, 0.        , 0.        , 0.        , 0.09810262,
       0.02579964, 0.04004899, 0.02297666, 0.06320861, 0.0740467 ,
       0.09669683, 0.02988232, 0.01181591, 0.21757995, 0.        ,
       0.09558273, 0.05669687, 0.13031493, 0.10348915, 0.07658256,
       0.00782183, 0.05548817, 0.        , 0.13275059, 0.03015608,
       0.00982597, 0.02268375, 0.01944077, 0.02470732, 0.01938536,
       0.        , 0.01472323, 0.04346962, 0.05349266, 0.05682825,
       0.        , 0.04382095, 0.04661655, 0.02407479, 0.05997693,
       0.01909076, 0.01860772, 0.06768198, 0.01611235, 0.03089472,
       0.        , 0.01383233, 0.10147977, 0.15192645, 0.14261487,
       0.05333933, 0.07285264, 0.05049889, 0.06632302, 0.03467296,
       0.05456952, 0.02657103, 0.02814174, 0.04263373, 0.00925353,
       0.01497405, 0.06672752, 0.        , 0.        , 0.        ,
       0.02232392, 0.02820083, 0.09169468, 0.        , 0.01553667,
       0.02216177, 0.02583855, 0.        , 0.        , 0.01666481,
       0.02581471, 0.10731452, 0.01955855, 0.14050262, 0.02543324,
       0.0907663 , 0.09099368, 0.13002916, 0.04603063, 0.08025483,
       0.01276075, 0.07071673, 0.00810998, 0.04151225, 0.        ,
       0.01157232, 0.03680051, 0.065663  , 0.01119556, 0.01672677,
       0.02452076, 0.01317156, 0.1324213 , 0.05595714, 0.02370113,
       0.0252046 , 0.        , 0.13152387, 0.05154022, 0.        ,
       0.02941513, 0.03349567, 0.        , 0.01804409, 0.19861983,
       0.01393435, 0.0889212 , 0.01779363, 0.01790853, 0.04964237,
       0.06675586, 0.01021868, 0.03355133, 0.05510575, 0.03768632,
       0.13057503, 0.01827179, 0.09523061, 0.08825721, 0.06076218,
       0.11418037, 0.08266546, 0.01054796, 0.02261499, 0.        ,
       0.16591675, 0.04572788, 0.03992728, 0.09973548, 0.11916537,
       0.05304176, 0.04939098, 0.03175053, 0.        , 0.08459863,
       0.05872517, 0.04027288, 0.13986986, 0.07543217, 0.1126297 ,
       0.07840756, 0.07278759, 0.02237173, 0.00250828, 0.        ,
       0.        , 0.03310451, 0.13750173, 0.03409882, 0.06760556,
       0.08865823, 0.04978724, 0.11499688, 0.06858337, 0.05907563,
       0.03278828, 0.01433797, 0.01869342, 0.0226465 , 0.        ,
       0.10568011, 0.0191643 , 0.01749666, 0.06256637, 0.01748144,
       0.10833052, 0.06766928, 0.07703866, 0.        , 0.01875995,
       0.        , 0.09078976, 0.07624704, 0.12748336, 0.0105352 ,
       0.121974  , 0.06824018, 0.10625431, 0.04406979, 0.01490713,
       0.02420398, 0.04427066, 0.01801563, 0.08909518, 0.11900247,
       0.        , 0.05065298, 0.01671836, 0.        , 0.07628905,
       0.03201239, 0.15062886, 0.07509215, 0.06246606, 0.02746391,
       0.        , 0.        , 0.11857887, 0.07248517, 0.04411519,
       0.01302091, 0.0195233 , 0.04182502, 0.07973517, 0.00814451,
       0.02648016, 0.0185885 , 0.02219174, 0.11393263, 0.        ,
       0.02282047, 0.05994046, 0.        , 0.05579672, 0.07935122,
       0.12687792, 0.01708614, 0.01087683, 0.07913428, 0.039796  ,
       0.02527453, 0.01781743, 0.0601359 , 0.07231593, 0.12745366,
       0.10807488, 0.01671546, 0.12210306, 0.04420968, 0.08925362,
       0.        , 0.22183479, 0.06665784, 0.        , 0.10937992,
       0.09701579, 0.00958215, 0.02372437, 0.        , 0.08228536,
       0.0368209 , 0.17208283, 0.02084403, 0.01590616, 0.0280742 ,
       0.06210013, 0.12954445, 0.09622321, 0.01547517, 0.10998998,
       0.09264529, 0.03210555, 0.02452076, 0.07034779, 0.11002631,
       0.01596282, 0.01367684, 0.01977438, 0.14058373, 0.        ,
       0.        , 0.00903116, 0.0197922 , 0.02708508, 0.        ,
       0.01803908, 0.01067101, 0.00876662, 0.17802357, 0.01385445,
       0.03587507, 0.10135372, 0.08286985, 0.05437101, 0.05705633,
       0.        , 0.0180732 , 0.07210172, 0.14061524, 0.06331105,
       0.        , 0.13416643, 0.06456252, 0.02702345, 0.04393659,
       0.01661298, 0.10116113, 0.09000596, 0.07353691, 0.07929489,
       0.10058193, 0.        , 0.01944981, 0.05051374, 0.01652028,
       0.0529064 , 0.01940558, 0.08645551, 0.11333464, 0.        ,
       0.06278367, 0.08055866, 0.        , 0.02556799, 0.01382455,
       0.0911898 , 0.0161538 , 0.01656097, 0.10558832, 0.0594582 ,
       0.12781382, 0.        , 0.0573265 , 0.        , 0.        ,
       0.05296779, 0.02083102, 0.0077665 , 0.02111952, 0.06559999,
       0.13871356, 0.05374402, 0.        , 0.08270382, 0.01421106,
       0.09316841, 0.        , 0.01540974, 0.        , 0.04336209,
       0.14745804, 0.        , 0.12085303, 0.11323603, 0.02140958,
       0.01826792, 0.01016387, 0.02342272, 0.00811441, 0.07342598,
       0.01698246, 0.06457711, 0.01988946, 0.11787484, 0.09023158,
       0.0551338 , 0.0265021 , 0.03985694, 0.04256798, 0.04801899,
       0.08257364, 0.00804924, 0.09122183, 0.0925734 , 0.        ,
       0.11313622, 0.0161689 , 0.01864347, 0.09270623, 0.11976104,
       0.08143258, 0.08277818, 0.04901469, 0.07384709, 0.04050211,
       0.05644072, 0.02026571, 0.02088506, 0.0593847 , 0.01760691,
       0.        , 0.04175923, 0.        , 0.        , 0.04768094,
       0.01210729, 0.        , 0.        , 0.04466905, 0.067548  ,
       0.09518323, 0.01580007, 0.0911887 , 0.07358213, 0.00323483,
       0.10224565, 0.04728128, 0.04979885, 0.        , 0.05596116,
       0.05842451, 0.0992843 , 0.        , 0.0694462 , 0.        ,
       0.12542555, 0.04409408, 0.14803611, 0.        , 0.01617749,
       0.04999135, 0.        , 0.07249541, 0.12033593, 0.00534858,
       0.064098  , 0.04990119, 0.0543672 , 0.10478866, 0.04572986,
       0.17729108, 0.10328163, 0.05932259, 0.05884982, 0.        ,
       0.        , 0.09654368, 0.10479805, 0.04063622, 0.0167788 ,
       0.        , 0.01098685, 0.23041012, 0.05102653, 0.03911561,
       0.0233896 , 0.0668881 , 0.04744589, 0.06657337, 0.09930446,
       0.01475473, 0.02235433, 0.01924502, 0.12517436, 0.10638001,
       0.07173002, 0.        , 0.08420138, 0.09964696, 0.0631429 ,
       0.07538694, 0.1171271 , 0.        , 0.17272734, 0.02101588,
       0.07153391, 0.        , 0.09508544, 0.06193936, 0.        ,
       0.17763427, 0.05701022, 0.03216795, 0.09073845, 0.02004113,
       0.02130369, 0.05953179, 0.0626006 , 0.11503765, 0.1563521 ,
       0.06558483, 0.01046994, 0.07851486, 0.16185691, 0.07132022,
       0.01599144, 0.15377874, 0.24264615, 0.16922331, 0.05148033,
       0.03799785, 0.06352928, 0.1328941 , 0.19708288, 0.17657715,
       0.01989949, 0.18407974, 0.01385905, 0.04623765, 0.11337695,
       0.12938351, 0.02004113, 0.07547949, 0.02172572, 0.11627236,
       0.00917965, 0.06166394, 0.08366537, 0.12226825, 0.03145566,
       0.06613256, 0.05976008, 0.02111582, 0.14104995, 0.07984611,
       0.        , 0.        , 0.01726948, 0.08740164, 0.03914057,
       0.13654317, 0.01399323, 0.09077603, 0.05146847, 0.04075879,
       0.0833307 , 0.05954915, 0.1307467 , 0.        , 0.03864239,
       0.02025752, 0.1597819 , 0.01755731, 0.14479175, 0.12902649,
       0.        , 0.05460828, 0.07101287, 0.06742509, 0.06018029,
       0.06341948, 0.17136758, 0.02292726, 0.01487592, 0.04998517,
       0.04373857, 0.        , 0.10271913, 0.0735544 , 0.11338575,
       0.02120388, 0.0563416 , 0.01921932, 0.0418337 , 0.09370759,
       0.09859824, 0.0239495 , 0.00159681, 0.09075668, 0.10499526,
       0.05713654, 0.01483917, 0.01889496, 0.09006289, 0.0168029 ,
       0.17071974, 0.04912985, 0.17397033, 0.05418214, 0.0581792 ,
       0.1105374 , 0.08739526, 0.00963486, 0.08963071, 0.06869203,
       0.0730293 , 0.        , 0.21271076, 0.00986941, 0.11841834,
       0.04208819, 0.13273939, 0.        , 0.11511685, 0.05933747,
       0.02589998, 0.12911579, 0.01582065, 0.08740346, 0.04760797,
       0.16637395, 0.1390345 , 0.09631288, 0.12102994, 0.03635496,
       0.03157109, 0.02264556, 0.06939828, 0.03062774, 0.02764801,
       0.02283479, 0.03882599, 0.13278075, 0.10729076, 0.01388247,
       0.02614678, 0.01898932, 0.06794868, 0.08185226, 0.14610389,
       0.06386534, 0.00975125, 0.        , 0.08367943, 0.05250146,
       0.08722157, 0.12286538, 0.05326174, 0.        , 0.06178518,
       0.01900081, 0.        , 0.01690888, 0.        , 0.11608616,
       0.07432008, 0.0820779 , 0.00671591, 0.07486236, 0.        ,
       0.03868444, 0.07715099, 0.07157072, 0.        , 0.06471902,
       0.02213172, 0.01429081, 0.032511  , 0.04591602, 0.00995685,
       0.00890497, 0.11130285, 0.06172108, 0.05204756, 0.0162674 ,
       0.11132415, 0.06754227, 0.03967511])

In [ ]:
# Recommendation function which takes the book name as input and returns the top 5 similar books based on the cosine similarity scores
def recommend_books(book_name):
    book_index = book_pivot.index.get_loc(book_name)
    similarity_scores = list(enumerate(similarity_score[book_index]))
    similarity_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)
    similarity_scores = similarity_scores[1:6]
    book_indices = [i[0] for i in similarity_scores]
    data = []
    for i in book_indices:
        item = []
        temp_df = books[books['Book-Title'] == book_pivot.index[i]]
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Title'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Author'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Image-URL-M'].values))
        data.append(item)
    return data

In [88]:
recommend_books('1984')

[['Animal Farm',
  'George Orwell',
  'http://images.amazon.com/images/P/0451526341.01.MZZZZZZZ.jpg'],
 ["The Handmaid's Tale",
  'Margaret Atwood',
  'http://images.amazon.com/images/P/0449212602.01.MZZZZZZZ.jpg'],
 ['The Catcher in the Rye',
  'J.D. Salinger',
  'http://images.amazon.com/images/P/0316769487.01.MZZZZZZZ.jpg'],
 ['Lord of the Flies',
  'William Gerald Golding',
  'http://images.amazon.com/images/P/0399501487.01.MZZZZZZZ.jpg'],
 ['Brave New World',
  'Aldous Huxley',
  'http://images.amazon.com/images/P/0060809833.01.MZZZZZZZ.jpg']]

In [89]:
import pickle

pickle.dump(book_pivot, open('book_pivot.pkl', 'wb'))
pickle.dump(similarity_score, open('similarity_score.pkl', 'wb'))
pickle.dump(books, open('books.pkl', 'wb'))